applications:
- salt
classes:
- service.salt.support
parameters:
  salt:
    minion:
      enabled: true
      source:
        engine: pkg
      local: true
      pillar:
        engine: reclass
        data_dir: /srv/salt/reclass
